cc_library(
    name = "exchange_connectivity_lib",
    srcs = ["exchange_connectivity.cpp"],
    hdrs = ["exchange_connectivity.h"],
    visibility = ["//visibility:public"],
    copts = ["-std=c++20"],
)
