cc_library(
    name = "ExchangeBookTypes",
    hdrs = ["ExchangeBookTypes.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "SharedTypes",
    hdrs = ["SharedTypes.h"],
    visibility = ["//visibility:public"],
    deps = [":ExchangeBookTypes"],
)